services:
  - type: web
    name: friendlywebbot-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: friendlywebbot-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
